apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploy everything into the "staging" namespace
namespace: staging

# Pull in the shared base + this environment's namespace
resources:
  - ../../base
  - namespace.yaml

# Override the image tag for staging
images:
  - name: ghcr.io/trobertsn/flask-api
    newTag: c413425302664fdbfb92e4595defdb140f042ea2

# Set replica count for staging
replicas:
  - name: flask-api
    count: 1
