apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploy everything into the "staging" namespace
namespace: staging

# Pull in the shared base + this environment's namespace
resources:
  - ../../base
  - namespace.yaml

# Override the image tag for staging
images:
  - name: ghcr.io/trobertsn/flask-api
    newTag: ad65d9209508c67f4abda6b6093ad9e9c76028ef

# Set replica count for staging
replicas:
  - name: flask-api
    count: 1
