apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploy everything into the "production" namespace
namespace: production

resources:
  - ../../base
  - namespace.yaml

# Override the image tag for production
images:
  - name: ghcr.io/trobertsn/flask-api
    newTag: e3cfdadf5628ddc68e905ac86b25a57f91cfea11

# Production runs 3 replicas
replicas:
  - name: flask-api
    count: 3
