apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploy everything into the "production" namespace
namespace: production

resources:
  - ../../base
  - namespace.yaml

# Override the image tag for production
images:
  - name: ghcr.io/trobertsn/flask-api
    newTag: ad65d9209508c67f4abda6b6093ad9e9c76028ef

# Production runs 3 replicas
replicas:
  - name: flask-api
    count: 3
